server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务进行路由
      routes:
        - id: payment_routh #路由ID，没有固定规则但要求唯一
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言，路径匹配的进行路由

        - id: payment_routh2 #路由ID，没有固定规则但要求唯一
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**  #断言，路径匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #是否从Eureka server 抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #表示是否将自己注册进入Eureka server ，默认为true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
