server:
  # 80表示注册到consul服务器的支付服务提供者端口号
  port: 80
spring:
  application:
    # 服务别名---注册consul到注册中心的名称
    name: cloud-consumer-oeder
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
