server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，自己职责是维护服务实例，不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      #单机版地址设置自己，集群设置为其他 eureka server
      #defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #关闭自我保护模式，保证不可用服务可以被及时剔除
    enable-self-preservation: false
    #时间间隔调整
    eviction-interval-timer-in-ms: 2000
